version: '3.9'

services:
  rabbitmq:
    container_name: 'at_rabbitmq'
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie'
    ports:
      - 5672:5672
      - 15672:15672

  db:
    container_name: 'at_postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5455:5432