# Generated by Django 3.2.3 on 2021-09-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.coin')),
            ],
        ),
    ]
