export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// Accounts
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const PASSWORD_RESET_TOKEN_CHECK_IN_PROGRESS = 'PASSWORD_TOKEN_CHECK_IN_PROGRESS';
export const PASSWORD_RESET_TOKEN_CHECKED = 'PASSWORD_TOKEN_CHECKED';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

// Trading
export const CHART_LOADING = "CHART_LOADING";
export const CHART_LOADED = "CHART_LOADED";
export const COIN_SELECTED = "COIN_SELECTED";
export const PERIOD_SELECTED = "PERIOD_SELECTED";
export const HEATMAP_LOADING = "HEATMAP_LOADING";
export const HEATMAP_LOADED = "HEATMAP_LOADED";
export const PREDICTION_CHART_LOADING = "PREDICTION_CHART_LOADING";
export const PREDICTION_CHART_LOADED = "PREDICTION_CHART_LOADED";
