# Generated by Django 3.2.4 on 2021-06-09 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 6, 9, 9, 10, 33, 770075))),
                ('user', models.CharField(max_length=128, unique=True)),
                ('user_location', models.CharField(max_length=128, null=True)),
                ('language', models.CharField(max_length=20)),
                ('hashtags', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=256)),
            ],
        ),
    ]
